spring:
  profiles:
    active: api-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level: 
    uk.co.aosd.flash: trace
    org.springframework: info
    org.hibernate: info
