spring:
  profiles:
    active: api-service

  datasource:
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level: 
    uk.co.aosd.flash: trace
    org.springframework: info
    org.hibernate: info



