spring:
  profiles:
    active: api-service, admin-service

  datasource:
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: always # Optional: helpful for debugging

logging:
  level: 
    uk.co.aosd.flash: trace
    org.springframework: info
    org.hibernate: info

springdoc.swagger-ui.path: "/swagger-ui.html"

